### PR TITLE
fix: Modify the validation rules of imageName on S2I page

### PR DESCRIPTION
**Pull request by fuchunlan**
Signed-off-by: lannyfu <lannyfu@yunify.com>

**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes ##1952

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:
image

```docs

```

### CODE REVIEW

**Comment by fuchunlan** [comment]
docker image :`2023f/ks-s2iform-rule`

**Comment by LinuxSuRen** [comment]
> 2023f/ks-s2iform-rule

This image does not work well. See also `standard_init_linux.go:219: exec user process caused: exec format error`

**Comment by LinuxSuRen** [comment]
When I try this PR with image `kubespheredev/ks-console:pr-fuchunlan-2088-dev` which built from https://github.com/kubesphere/console/pull/2088/commits/551ed4fc17106d42236fb08d84ab115437988491, I got the following errors:

image

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
Test failed with image `surenpi/ks-console:s2iform-rule-dev@sha256:2439ce1621868b8ba12ecaf61afe759471c637d128da45173b9b7deb0ba203ff`, the git ref is https://github.com/kubesphere/console/pull/2088/commits/b15293760231b5ebe62efdcb9fc869beaa0929b8

image

**Comment by JohnNiang** [comment]
There is a potential useful document about [docker image name](https://cloud.google.com/artifact-registry/docs/docker/names).

**Comment by JohnNiang** [comment]
@fuchunlan I suggest you write some tests against the regex, `PATTERN_IMAGE_NAME`.

**Comment by fuchunlan** [comment]
> There is a potential useful document about [docker image name](https://cloud.google.com/artifact-registry/docs/docker/names).

Does the regex of the image name need to match all ?
image

**Comment by fuchunlan** [comment]
5A195B2121AE066B11D516ED3BF14E69

**Review by LinuxSuRen — COMMENTED** [review]
I've tested it manually. LGTM

**Comment by JohnNiang** [comment]
I've tested in my local environment manually. LGTM

**Pull request merged**
