### PR TITLE
fix: Fix the webhook url in the single cluster

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #[#kubesphere/kubesphere/3857](https://github.com/kubesphere/kubesphere/issues/3857)

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

/assign @LinuxSuRen

### CODE REVIEW

**Comment by harrisonliu5** [comment]
Could you provide me with a single cluster environment @LinuxSuRen?

**Comment by LinuxSuRen** [comment]
> Could you provide me with a single cluster environment @LinuxSuRen?

It is very easy to set up an environment. You can use this command: `ks install k3d --components devops`

Download the CLI [ks](https://github.com/LinuxSuRen/ks/) from [here](https://github.com/LinuxSuRen/ks/releases).

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
It does not work well when I test it under a multi-cluster environment. Please see the following output:

```
curl "http://localhost:8000/cluster/host/devops_webhook/git/?url=https://gitee.com/devops-ws/learn-pipeline-java"
Redirecting to <a href="/login?referer=/cluster/host/devops_webhook/git/">/login?referer=/cluster/host/devops_webhook/git/</a>.
```

The following API request is ok:
```
curl "http://localhost:8000/devops_webhook/git/?url=https://gitee.com/devops-ws/learn-pipeline-java"
No git jobs using repository: https://gitee.com/devops-ws/learn-pipeline-java and branches:
Scheduled indexing of testk682v � git
Scheduled indexing of testg8tmh � git1
```

**Comment by LinuxSuRen** [comment]
Any update? @harrisonliu5

**Comment by harrisonliu5** [comment]
> Any update? @harrisonliu5
Remove the cluster in a single cluster, but you did not tell me if you need the cluster in multiple clusters

**Comment by LinuxSuRen** [comment]
> but you did not tell me if you need the cluster in multiple clusters

As you can see [here](https://github.com/kubesphere/console/pull/1873#pullrequestreview-657397434). There's no difference between the single cluster and multi-cluster environment.

**Comment by harrisonliu5** [comment]
> > but you did not tell me if you need the cluster in multiple clusters
> 
> As you can see [here](https://github.com/kubesphere/console/pull/1873#pullrequestreview-657397434). There's no difference between the single cluster and multi-cluster environment.

The cluster name of a single cluster is default, and the main cluster is called host in a multi-cluster environment

**Comment by LinuxSuRen** [comment]
> The cluster name of a single cluster is default, and the main cluster is called host in a multi-cluster environment

According to my tests, the following API calling always works well (in a single cluster or multi-cluster). You can test it by yourself.

`curl "http://localhost:8000/devops_webhook/git/?url=https://gitee.com/devops-ws/learn-pipeline-java"`

**Comment by harrisonliu5** [comment]
image

**Comment by harrisonliu5** [comment]
image

**Comment by LinuxSuRen** [comment]
I built a docker image against this PR `ghcr.io/linuxsuren/console/ks-console:gitpod-dev`. You can use it if you want to help to test it.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
