### PR TITLE
fix typo in container settings page

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Signed-off-by: FeynmanZhou <zpf0610@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

 /kind documentation

> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
for https://github.com/kubesphere/kubesphere/issues/1927

**Comment by rayzhou2017** [comment]
2.1.1 is already released, so this fix is going to be in 3.0.0, right?

**Pull request merged**
