### PR TITLE
fix: Change the pipeline api from v2 to v3

### PR DESCRIPTION
**Pull request by harrisonliu5**
### What type of PR is this?

/kind bug
/kind api-change

### Which issue(s) this PR fixes:

- fix https://github.com/kubesphere/console/issues/2294
- fix https://github.com/kubesphere/console/issues/2295
- fix https://github.com/kubesphere/console/issues/2296
- fix https://github.com/kubesphere/console/issues/2297

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Change the pipeline api from v2 to v3
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Thanks for your rectification for DevOps! @harrisonliu5 . I will test it manually later.

**Comment by LinuxSuRen** [comment]
fix https://github.com/kubesphere/console/issues/2297

**Comment by JohnNiang** [comment]
Fix https://github.com/kubesphere/ks-devops/issues/268

**Review by chenz24 — APPROVED** [review]

**Review by LinuxSuRen — COMMENTED** [review]
lgtm

**Pull request merged**
