### PR TITLE
feat: Website static link control

### PR DESCRIPTION
**Pull request by weili520**
Signed-off-by: TheYoungManLi <cjl@kubesphere.io>

### What type of PR is this?
/kind  feature

### Which issue(s) this PR fixes:
Fixes #

### Does this PR introduced a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by weili520** [comment]
/cc @harrisonliu5 
most of link href is document url.

**Comment by zheng1** [comment]
@weili520 Please fix the conflict

**Comment by weili520** [comment]
> @weili520 Please fix the conflict
done

**Comment by harrisonliu5** [comment]
I think this PR did not achieve the expected effect. @zheng1

**Comment by zheng1** [comment]
/hold

> I think this PR did not achieve the expected effect. @zheng1

**Review by weili520 — COMMENTED** [review]
@harrisonliu5  all done, please take a look about it.

**Review by weili520 — COMMENTED** [review]
:)

**Review by weili520 — COMMENTED** [review]
:)

**Review by weili520 — COMMENTED** [review]
🔢

**Review by weili520 — COMMENTED** [review]
:)

**Pull request merged**
