### PR TITLE
fix: Fix the branch name not encode.

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>

### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/console/issues/2747

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
hi @luoyuctl this is the front-end part of the git branch name-related issue. Feel free to help us to test it. Thanks!

**Review by JohnNiang — APPROVED** [review]
LGTM.

This fix works very well.

image

**Comment by JohnNiang** [comment]
I've verified this issue, please refer to https://github.com/kubesphere/console/pull/2734#pullrequestreview-823231155.
/close

**Comment by luoyuctl** [comment]
> hi @luoyuctl this is the front-end part of the git branch name-related issue. Feel free to help us to test it. Thanks!

t has been verified that there is no problem, but there is still one last problem to fix . see https://github.com/kubesphere/ks-devops/issues/400.

**Pull request merged**
