### PR TITLE
fix: Compatible with version 3.2 of Devops

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>

### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/console/issues/3265 #https://github.com/kubesphere/console/issues/3280
 
### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
It failed when I try to test it with the Bitbucket cloud in v3.2.0. In my opinion, this is a known issue. We can document it.

hi @wenxin-01 , what do you think?


image

**Comment by wenxin-01** [comment]
> It failed when I try to test it with the Bitbucket cloud in v3.2.0. In my opinion, this is a known issue. We can document it.
> 
> hi @wenxin-01 , what do you think?
> 
> image

In my opinion, we can prompt users in the documentation that bitbucket cloud is not available in version 3.2, and recommend users to upgrade to 3.3.0

**Review by LinuxSuRen — COMMENTED** [review]
I have tested it manually. It works well. Thanks for your effort! Good job!
LGTM

**Pull request merged**
