### PR TITLE
fix: Fix the repo selected is incorrect after search

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```
/assign @leoendless 
/project devops

### CODE REVIEW

**Comment by zheng1** [comment]
Can you provide screenshots before and after the modification, so that we can quickly see the effect of this PR? @harrisonliu5

**Review by LinuxSuRen — APPROVED** [review]
/unhold
/lgtm

I didn't go through the code lines. The manual test looks good.

**Comment by harrisonliu5** [comment]
before 

https://user-images.githubusercontent.com/17872673/114161045-3037c600-995a-11eb-8a79-aee24574f445.mp4

**Comment by harrisonliu5** [comment]
after

https://user-images.githubusercontent.com/17872673/114161128-4d6c9480-995a-11eb-89f0-61cb64ffc6ff.mp4

**Pull request merged**
