### PR TITLE
fix: Render wrong form item while multiple branch

### PR DESCRIPTION
**Pull request by EliChen95**
### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/ks-devops/issues/537

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by harrisonliu5 — APPROVED** [review]

**Review by LinuxSuRen — APPROVED** [review]
I have tested it with the following image. It works well. Thanks for your effort @EliChen95 

```
kubespheredev/ks-console:fix-render-wrong-form-item
```

**Pull request merged**
