### PR TITLE
fix: fix UI and style bug

### LINKED ISSUE #2051: UI bug
**Describe the bug**
1. App Introduction and App Description are reversed
2. no scroll bar, so the screenshot of the application cannot be displayed completely. When the introduction of the application is a lot of content

### PR DESCRIPTION
**Pull request by moweiwei**
Signed-off-by: moweiwei <moweiwei6@gmail.com>

> /kind bug

Fixes #2051

/assign @zheng1
/approve @zheng1

### CODE REVIEW

**Comment by fuchunlan** [comment]
There is a scrollbar in this page, but it is not shown.In addition, you deleted `bottom: 0 !important;`, which makes too much margin on bottom

**Comment by moweiwei** [comment]
@fuchunlan When the application description (actually it should be the application introduction) is high, there is no scroll bar

**Comment by moweiwei** [comment]
@fuchunlan  When the application description (actually it should be the application introduction) is high, there is no scroll bar，As a result, the screenshot of the application below cannot be displayed completely

**Comment by moweiwei** [comment]
@fuchunlan When the application description (actually it should be the application introduction) is very very high, there is no scroll bar，As a result, the screenshot of the application below cannot be displayed completely

**Review by fuchunlan — APPROVED** [review]

**Comment by zheng1** [comment]
Wait someone from @kubesphere/sig-docs

**Pull request closed without merging**
