### PR TITLE
fix: Do not translate "ConfigMap" into "配置" and "Secret" into "密钥". #2035

### PR DESCRIPTION
**Pull request by live77**
### What type of PR is this?
/kind bug

### What this PR does / why we need it:

Do not translate "ConfigMap" into "配置" and "Secret" into "密钥". #2035

"密钥" means a private key or public key used to encrypt or decrypt certain information.
"配置" means a software or hardware configuration.
Both are too general and misleading. ConfigMap and Secret are concepts unique to Kubernetes, and we should not translate them.

### Which issue(s) this PR fixes:

Fixes # 2035

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

/assign @Patrick-LuoYu  @harrisonliu5 
Here is the logic of "Do Not Translate"

```docs

Do Translation Rules

保密字典 -> Secrets, Secret 
密钥 -> Secret
密鑰 -> Secret

配置字典 -> ConfigMap, ConfigMaps
配置 -> ConfigMap （in some cases）


```

### CODE REVIEW

**Comment by Felixnoo** [comment]
Hi, thanks for your contribution. The UI text is currently [under optimization](https://github.com/kubesphere/kubesphere/issues/4076) and `Secret` will be translated into `保密字典` and `ConfigMap` into `配置字典`。

**Comment by Felixnoo** [comment]
@Patrick-LuoYu 
Hi, I think you could close [this issue](https://github.com/kubesphere/console/issues/2035)?

**Comment by live77** [comment]
> Hi, thanks for your contribution. The UI text is currently [under optimization](https://github.com/kubesphere/kubesphere/issues/4076) and `Secret` will be translated into `保密字典` and `ConfigMap` into `配置字典`。

I see , thanks for the reply. I'll cancel the PR.

**Pull request closed without merging**
