### PR TITLE
fix: Fix gitlab source repo options error

### PR DESCRIPTION
**Pull request by yazhouio**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:
fix: Fix gitlab source repo options error
### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/ks-devops/issues/1039

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
none
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by donniean — APPROVED** [review]

**Comment by yudong2015** [comment]
fixed: #4272

**Pull request merged**
