### PR TITLE
update: Update tc locales, progress to node.js completed

### PR DESCRIPTION
**Pull request by turtlechang**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by leoendless** [comment]
Please use `git commit -s` to commit your changes with signature.

**Comment by leoendless** [comment]
Some of old commits are still missing signature. You need to squash the old commits.

**Comment by turtlechang** [comment]
@leoendless Which commits need to compress old ones? My turtle/console seems to be messed up. Do I need to fork again?

**Comment by leoendless** [comment]
> @leoendless Which commits need to compress old ones? My turtle/console seems to be messed up. Do I need to fork again?

Yes, you can also fork again and commit the changes in one record.

**Comment by turtlechang** [comment]
@leoendless This PR can be deleted, I have forked again, wait for my new PR again, thank you

**Pull request closed without merging**
