### PR TITLE
fix: use chinese characters as password

### LINKED ISSUE #3271: Can't log in when setting Chinese characters as password
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When the user changes the last digit of the password to Chinese characters such as `P@88w0rd）` , the change will pass, but the user will not be able to log in.

**Expected behavior**
Disable Chinese characters or fix stuck at login

### PR DESCRIPTION
**Pull request by OrangeBao**
replace window.btoa with safeBtoa 

### What type of PR is this?
/kind bug

### Which issue(s) this PR fixes:

Fixes #3271 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by OrangeBao** [comment]
Compatible with the original user password~

**Comment by harrisonliu5** [comment]
We will ban Chinese characters in passwords later, thank you for your time and effort for us.

**Comment by OrangeBao** [comment]
> We will ban Chinese characters in passwords later, thank you for your time and effort for us.

Tell me the password rules and I'll do this~

**Comment by harrisonliu5** [comment]
> > We will ban Chinese characters in passwords later, thank you for your time and effort for us.
> 
> @harrisonliu5 Tell me the password rules and I'll do this~

The password rule is "contain at least one number, one lowercase letter, and one uppercase letter. The length must be 8 to 64 characters" @OrangeBao

**Comment by OrangeBao** [comment]
> > > We will ban Chinese characters in passwords later, thank you for your time and effort for us.
> > 
> > 
> > @harrisonliu5 Tell me the password rules and I'll do this~
> 
> The password rule is "contain at least one number, one lowercase letter, and one uppercase letter. The length must be 8 to 64 characters" @OrangeBao

consists only of letters and numbers？ @harrisonliu5

**Comment by harrisonliu5** [comment]
Thank you for your contribution, this PR will be closed soon, if you are still interested in this issue, please continue to pay attention to our latest progress, and hope to help us at that time, thank you

**Pull request closed without merging**
