### PR TITLE
fix: enter a number with two places of decimal directly and limit input maximum

### LINKED ISSUE #2102: Setting workspace/ project/pod quota error
Describe the bug
Two issues occurred when setting resource requests and resource limits with the keyboard in the workspace/ project/pod quota.

Versions used
KubeSphere: v3.1.1-dirty

To Reproduce
1. Go to page 'The workspace/project/pod quota'
2. Use the keyboard to set resource requests and resource limits.
3. The first issue:
    When you need to enter a decimal, you must enter two decimal points in a row to display it.
4. The second issue:
    There are no restrictions in resources limit input maximum.When the input enough digital display the results do not tally with the input data. When I enter many number 8 results are as follows.
    
image
/kind bug
/assign @kubesphere/sig-console
/priority medium

### PR DESCRIPTION
**Pull request by weili520**
### What type of PR is this?
/kind bug

### Which issue(s) this PR fixes:
Fixes ##2102

### Special notes for reviewers:
(1) now, we can enter a number with two places of decimal, eg: 0.02, 3.23.

https://user-images.githubusercontent.com/33231138/127299025-64cb4586-7486-4b96-b6e1-664398ae7ef8.mov

(2) we can not input a number bigger than 8, the maximum is from the props, it 's default value is 4(cpu)/8000(memory)

https://user-images.githubusercontent.com/33231138/127299064-87ec9fd8-f47e-4b1d-bf7f-a394c3bb3b79.mov

### Does this PR introduced a user-facing change?

```release-note
fix: enter a number with two places of decimal directly and limit input maximum. (#2102, @weili520  )
```

### CODE REVIEW

**Comment by weili520** [comment]
the error in the second video has been resolved. 
it caused by the checkError function will in work when the input number as '0.'.
 
截屏2021-08-17 15 50 46

**Comment by weili520** [comment]
the error in the second video has been resolved. 
it caused by the checkError function will in work when the input number as '0.'.
截屏2021-08-17 15 50 46

**Comment by zheng1** [comment]
Please following [these notes](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md#applying-a-release-note) to add release notes into the pull request content.

**Pull request merged**
