### PR TITLE
Update Traditional Chinese translations

### PR DESCRIPTION
**Pull request by ydFu**
* The commit rephrased some words and sentences for Traditional Chinese translations

Signed-off-by: ydFu <ader.ydfu@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

 /kind optimization

**What this PR does / why we need it**:

* The commit rephrased some words and sentences for Traditional Chinese translations

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by turtlechang** [comment]
Excellent!!
I don’t see the difference between "没" and "沒", thank you for your modification.

**Comment by ydFu** [comment]
@turtlechang 
Thank, hope to help the community

**Pull request merged**
