### PR TITLE
fix: Verify devops project name input

### LINKED ISSUE #2707: Add verification for devops project name input
**Describe the bug**
suggestion: Add verification for name input 
image

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Low

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What type of PR is this?

/kind bug
/area devops

### Which issue(s) this PR fixes:

Fixes #2707

### Special notes for reviewers:
```
```
The screentshot like below:
image

### Does this PR introduced a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mangoGoForward** [comment]
Hold until the [PR] of #kubesphere/ks-devops#435 is merged. 
/hold
/cc @kubesphere/sig-devops

**Review by LinuxSuRen — COMMENTED** [review]
@mangoGoForward thanks for your really quick action. I have tested this PR manually. It works well.

I built the frontend image via [gitpod](https://gitpod.io/#https://github.com/mangoGoForward/console/tree/fix/verify-devops-project-name).

`surenpi/ks-console:latest@sha256:34b81e20daf49c6fc0ddf099c39549571931cecf9c0eee5a9d990856c38b8994`

/lgtm

**Review by JohnNiang — COMMENTED** [review]
I'm sorry that I have no time to test this fix manually. But code looks good to me.
LGTM

**Pull request merged**
