### PR TITLE
Update UI text on Jobs and CronJobs pages

### PR DESCRIPTION
**Pull request by serenashe**
Signed-off-by: adakisme <serenashe@yunify.com>

### What type of PR is this?
/kind documentation

### What this PR does / why we need it:
I update the UI text on Jobs and CronJobs pages. There is no change in the source code logic.
Please take a look, thanks!

/assign @harrisonliu5

### CODE REVIEW

**Comment by serenashe** [comment]
@Felixnoo Hi Felix, please take a look. I think there is no overlap between the changes we've made. 👀

**Comment by Felixnoo** [comment]
> @Felixnoo Hi Felix, please take a look. I think there is no overlap between the changes we've made. 👀

@serenashe Yes, no overlap.  👀

**Pull request merged**
