### PR TITLE
fix: Change the color of the button on the Metering and Billing page.

### PR DESCRIPTION
**Pull request by fuchunlan**
Signed-off-by: lannyfu <lannyfu@yunify.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes ##1818

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:
image
image

```docs

```

### CODE REVIEW

**Comment by harrisonliu5** [comment]
What about in the disabled state？

**Comment by fuchunlan** [comment]
> What about in the disabled state？

The color in the disabled state is same as the '<' button.
image

**Pull request merged**
