### PR TITLE
fix:the associated hpa hasn't been deleted when use the command line to delete the deployment

### PR DESCRIPTION
**Pull request by zhaohuiweixiao**
Signed-off-by: zhaohuihui <zhaohuihui_yewu@cmss.chinamobile.com>

### What type of PR is this?
/kind bug

### What this PR does / why we need it:
The associated hpa hasn't been deleted when use the command line to delete the deployment.
hpa删除

### Special notes for reviewers:
```
/assign @patrick-luoyu
```

### Does this PR introduced a user-facing change?
```release-note
None
```

### CODE REVIEW

**Review by harrisonliu5 — APPROVED** [review]

**Comment by zhaohuiweixiao** [comment]
I run the docker build successfully in local environment.
image

**Pull request merged**
