### PR TITLE
fix: Fix the price data with less 0

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes [#kubesphere/kubesphere/3747](https://github.com/kubesphere/kubesphere/issues/3747)

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

/assign @zheng1 
/assign @LinuxSuRen 
/project devops

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
If this PR could fix the corresponding issue, please fix the comment from

`Fixes ##kubesphere/kubesphere/3747`

to

`Fixes #kubesphere/kubesphere/3747`

By the way, I don't really understand the front-end code lines. So would you mind providing the screenshots which contain the before one and the after one?

**Comment by LinuxSuRen** [comment]
hi @yunkunrao, please help to verify this PR. Thanks!

**Comment by harrisonliu5** [comment]
after

image

**Comment by harrisonliu5** [comment]
before
image

**Pull request merged**
