### PR TITLE
fix: Fix the pipeline detail page could not use the browser go back button

### LINKED ISSUE #1928: Couldn't go back one page at pipeline detail page
**Describe the bug**

Couldn't go back one page at pipeline detail page.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: latest-dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
1 masters:  8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**
1. Go to single pipeline page
2. Click **Go back one page <--** button in browser
3. See error

**Expected behavior**

Go back one page when I click **Go back one page <--** button in browser.

/kind bug
/area devops
/priority high

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1928

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```
/assign @JohnNiang

### CODE REVIEW

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/120984599-66a08e80-c7ad-11eb-9e07-23dda24a0cc3.mp4

**Comment by JohnNiang** [comment]
Thanks for your fix. I confirm that it works for me in my local environment.

**Pull request merged**
