### PR TITLE
feat: Add credential in github and bitbucket

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes [#kubesphere/kubesphere/3675](https://github.com/kubesphere/kubesphere/issues/3675)

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

/assign @leoendless 
/area devops

### CODE REVIEW

**Comment by harrisonliu5** [comment]
Need to wait until @LinuxSuRen  have completed the test before merging

**Comment by LinuxSuRen** [comment]
hi @leoendless I have not done with the test. Please see https://github.com/kubesphere/console/pull/1761#issuecomment-814555594

**Comment by leoendless** [comment]
My mistake. Please create a new hotfix pr if there are some problems. @harrisonliu5

**Comment by LinuxSuRen** [comment]
> My mistake. Please create a new hotfix pr if there are some problems. @harrisonliu5

No worries. I just want to do more tests before it gets merged. Maybe we can add a `/hold` label to make it be clear.

**Pull request merged**
