### PR TITLE
WIP:update: modify EventSearch page and related component

### PR DESCRIPTION
**Pull request by weili520**
Signed-off-by: TheYoungManLi <1512298456@qq.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

> /kind optimization

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```
/assign  @leoendless

### CODE REVIEW

**Review by weili520 — COMMENTED** [review]
viewed

**Review by weili520 — COMMENTED** [review]
reviewed

**Comment by zryfish** [comment]
/hold 
We are going to release v3.1.0 next week, this PR is too large to merge now.

**Pull request closed without merging**
