### PR TITLE
fix(alert-policy-page): alert target item incomplete

### LINKED ISSUE #60: 告警规则监控列表这里不是全部
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**

For UI issues please also add a screenshot that shows the issue.

需要检查 resource kapi，应该做了分页（默认 limit=10，page=1）。api 返回里写了 total_count=12）。没有处理分页，所以只展示了10个item，而不是全部监控目标

image

image

image

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**

### PR DESCRIPTION
**Pull request by justahole**
**What type of PR is this?**

> /kind bug

**Which issue(s) this PR fixes**:
Fixes #60

### CODE REVIEW

**Comment by leoendless** [comment]
should refact the list with paging

**Comment by justahole** [comment]
There is no need to refactor, cause both AlertPolicy and AlertRules use old API.

**Comment by leoendless** [comment]
> There is no need to refactor, cause both AlertPolicy and AlertRules use old API.

Is it because the old API does not support pagination?

**Comment by leoendless** [comment]
replaced by https://github.com/kubesphere/console/pull/79

**Pull request closed without merging**
