### PR TITLE
fix: Support the logs wrapping

### PR DESCRIPTION
**Pull request by ChroNusscar**
### What type of PR is this?

/kind bug

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ChroNusscar** [comment]
before:
image
after:
image

**Comment by harrisonliu5** [comment]
/assign @weili520
please review it, thanks.

**Pull request merged**
