### PR TITLE
update https://registry.npm.taobao.org to https://registry.npmmirror.com

### PR DESCRIPTION
**Pull request by npmmirror**
Update https://registry.npm.taobao.org to https://registry.npmmirror.com, Please refer to https://zhuanlan.zhihu.com/p/430580607.

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
/lgtm

Please refer to
- https://github.com/cnpm/cnpm/issues/361

**Review by weili520 — COMMENTED** [review]
👍

**Comment by JohnNiang** [comment]
Please be aware that the author is a bot.

**Pull request merged**
