### PR TITLE
fix: Fix the bugs when add volume with same pvc.

### LINKED ISSUE #3571: bugs when add volumes with same pvc in workload
There is a bug when trying to add volumes with same pvc in workload. 
Here are the screenshots when tring to add volumes with same pvc in deployment:

- Add the first volume with pvc `test`, mountPath is `/a`:

image

- Add result, generated volumeName is `volume-9tvz9h`:

image

- Add the second volume with pvc `test`, mountPath is `/b`:
image

- Add result, generated volumeName is `volume-gyabrs`:
image

As these screenshots show:

- mountPath `/a` of the first volume  `volume-9tvz9h` will replaced as `/b`;
- and mountPath of the second volume `volume-gyabrs` will be none.

kubesphere version: 3.3.0

### PR DESCRIPTION
**Pull request by smile-luobin**
Signed-off-by: smile-luobin <smile.luobin@gmail.com>

### What type of PR is this? ###

/kind bug

### Which issue(s) this PR fixes: ###

fix #3571

### Does this PR introduced a user-facing change?

```release-note
NONE
```

### Additional documentation, usage docs, etc.: ###

    NONE

### CODE REVIEW

**Comment by harrisonliu5** [comment]
Thank you for your contribution, please refer to other PR formats to modify your PR.

**Comment by smile-luobin** [comment]
> Thank you for your contribution, please refer to other PR formats to modify your PR.

maybe done.

**Comment by harrisonliu5** [comment]
In your code, there is no mountPath.

image

**Comment by smile-luobin** [comment]
> In your code, there is no mountPath.
> 
> image

done.

**Comment by smile-luobin** [comment]
> In your code, there is no mountPath.
> 
> image

done

**Comment by harrisonliu5** [comment]
Thank you very much for your quick response, however, the same PVC can only be mounted on one, so a better way is to add an error message on this basis, I hope to get your feedback, thank you.

**Comment by smile-luobin** [comment]
> 

`the same PVC can only be mounted on one`? why?

**Comment by smile-luobin** [comment]
> Thank you very much for your quick response, however, the same PVC can only be mounted on one, so a better way is to add an error message on this basis, I hope to get your feedback, thank you.

Why `the same PVC can only be mounted on one`? Is not supported in K8s?

**Comment by harrisonliu5** [comment]
> 

yes

**Comment by harrisonliu5** [comment]
> > Thank you very much for your quick response, however, the same PVC can only be mounted on one, so a better way is to add an error message on this basis, I hope to get your feedback, thank you.
> 
> Why `the same PVC can only be mounted on one`? Is not supported in K8s?
yes

**Pull request closed without merging**
