### PR TITLE
Add Jenkins overview monitoring template

### PR DESCRIPTION
**Pull request by JohnNiang**
Add Jenkins overview monitoring template for adding Jenkins monitoring conveniently. 

Please follow up <https://github.com/kubesphere/kubesphere/issues/3814>.

Upstream PRs are: <https://github.com/kubesphere/ks-jenkins/pull/27>, <https://github.com/kubesphere/ks-installer/pull/1490>.

There has a built docker image for test: `johnniang/ks-console:jenkins-monitoring`.

/kind feature

image
image

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Please don't forget to check the ci status once you believe your PR is ready.

**Comment by JohnNiang** [comment]
> Add Jenkins overview monitoring template for adding Jenkins monitoring conveniently.
> 
> Please follow up [kubesphere/kubesphere#3814](https://github.com/kubesphere/kubesphere/issues/3814).
> 
> There has a built docker image for test: `johnniang/ks-console:jenkins-monitoring`.
> 
> /kind feature

image
image

**Comment by LinuxSuRen** [comment]
Consider there're three commits in this PR. Please consider the following steps (or better ideas):

* squash your commits into one
* make this merge method to be `squash` by filing a PR to [prow](https://github.com/kubesphere/prow-tutorial/blob/master/ks-ci-bot/config.yaml#L19)

**Comment by JohnNiang** [comment]
> Consider there're three commits in this PR. Please consider the following steps (or better ideas):
> 
> * squash your commits into one
> * make this merge method to be `squash` by filing a PR to [prow](https://github.com/kubesphere/prow-tutorial/blob/master/ks-ci-bot/config.yaml#L19)

WIP.

**Pull request merged**
