### PR TITLE
fix: Container logs do not display full Spaces.

### PR DESCRIPTION
**Pull request by ruibaby**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Display log contents correctly.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

| before | After |
| ------ | ----- |
|    Snipaste_2021-07-12_23-41-44 |  Snipaste_2021-07-12_23-41-26 |
|   Snipaste_2021-07-12_23-46-58 |  Snipaste_2021-07-12_23-46-45 |

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @ruibaby , please sign off your commit.

**Comment by JohnNiang** [comment]
Thank @ruibaby  for first contribution to KubeSphere.

/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
Thank @ruibaby for your contribution to KubeSphere

/approve

**Comment by harrisonliu5** [comment]
fix: #https://github.com/kubesphere/console/issues/1257

**Pull request merged**
