### PR TITLE
fix: Modify the description and default value about old branches discard

### LINKED ISSUE #2149: Unclear description about old branches discard on the multi-branch Pipeline setting page
**Describe the bug**

Screenshot from Jenkins:
image

Screenshot from DevOps page:
image

This feature will remove those plugins that have been deleted from the git repository.

## Typo

`Discard old branch` should be `Discard old branches`

## Default values improvement

I suggest that we change the following default values:

* `Days to keep old branches` be 7
  * keep the old branches for a week
* `Max number of branches to keep` be 5

/area devops
/priority high
/help
/milestone v3.2

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: latest

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the DevOps page
2. Create a multi-branch Pipeline
3. Check the description

**Expected behavior**
Having a clear and correct description.

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes #2149

### CODE REVIEW

**Comment by harrisonliu5** [comment]
After
image

image

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
I guess you forget to fix the typo:

`Discard old branch` should be `Discard old branches`

**Comment by harrisonliu5** [comment]
> I guess you forget to fix the typo:
> 
> `Discard old branch` should be `Discard old branches`

done

**Review by LinuxSuRen — COMMENTED** [review]
I'm not able to review the code lines. But it's good from the screenshot image.

/lgtm

**Comment by harrisonliu5** [comment]
image

**Comment by Felixnoo** [comment]
/cc @kubesphere/sig-docs 
UI description changed.

**Pull request merged**
