### PR TITLE
PERF: hide table action menu when project is terminating

### PR DESCRIPTION
**Pull request by OrangeBao**
### What type of PR is this?

/kind feature

### What this PR does / why we need it:

If you modify a project which is terminating, you will get a error Message。

### Which issue(s) this PR fixes:

Fixes # None

### Special notes for reviewers:
```
@24sama 
```

### Does this PR introduced a user-facing change?

image

### CODE REVIEW

**Comment by OrangeBao** [comment]
@harrisonliu5  is this pr 'lgtm'?

**Comment by VioZhang** [comment]
> @harrisonliu5 is this pr 'lgtm'?

Consider to the augmentability i'd suggest that we'd better not delete it, because the operation of the button cause nothing when we have deleted the ns and deleting it may causing other problems. If oneday we could support the"undelete" feature,the buttun is useful.

**Comment by harrisonliu5** [comment]
This PR will be closed soon, thank you for your contribution, thank you.

**Pull request closed without merging**
