### PR TITLE
fix: Change pvc access modes to list 

### LINKED ISSUE #2183: Change pvc access modes to list
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
Current the access mode is a single selection, but it should be a string array in fact.
For UI issues please also add a screenshot that shows the issue.
image

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

https://github.com/kubesphere/kubesphere/issues/4089

### PR DESCRIPTION
**Pull request by live77**
### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes #2183

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Change pvc access modes to list
```

### Additional documentation, usage docs, etc.:

```docs

```
截屏2021-09-28 下午7 05 56

### CODE REVIEW

**Comment by f10atin9** [comment]
Considering that most users do not need to manually set the access mode, and RWO is the most commonly used mode.

I suggest setting a default value, the logic is as follows:

- If the console can get the annotation and the length is greater than 0:
If there is RWO, RWO is checked by default, otherwise, the first value in the list is checked by default.

- If annotations cannot be found or the number of modes is 0:
Think that all three modes are available, and RWO is also checked by default.

**Comment by f10atin9** [comment]
The text in the red box can be removed, a title like "ReadWriteOnce" is enough. 

image

**Comment by live77** [comment]
> Considering that most users do not need to manually set the access mode, and RWO is the most commonly used mode.
> 
> I suggest setting a default value, the logic is as follows:
> 
> * If the console can get the annotation and the length is greater than 0:
>   If there is "ReadWriteOnce",  "ReadWriteOnce"is checked by default, otherwise, the first value in the list is checked by default.
> * If annotations cannot be found or the number of modes is 0:
>   Think that all three modes are available, and "ReadWriteOnce" is also checked by default.

Thanks for the review,  will fix it based on your suggestion.

**Comment by live77** [comment]
> The text in the red box can be removed, a title like "ReadWriteOnce" is enough.
> 
> image

fixed.

**Comment by harrisonliu5** [comment]
/approve
Thanks for your contribution : )

**Pull request merged**
