### PR TITLE
refactor: Reuse the git repository selector on the Pipeline and CD page

### PR DESCRIPTION
**Pull request by bunnymiao**
### What type of PR is this?

/kind feature

### What this PR does / why we need it:
Reuse the git repository selector on the Pipeline and CD page
### Which issue(s) this PR fixes:

Fixes #[606](https://github.com/kubesphere/ks-devops/issues/606)

### Special notes for reviewers:
image

image

image

image

image

### Does this PR introduced a user-facing change?

```release-note
NONE
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bunnymiao** [comment]
I have tested it with the following image:

After creating a new code repo, select it automatically. ✅
Use svn code repo directly. ✅
Use git repo.✅
Create same code repo with different name and select one of them✅
select code repo in CD page✅

**Comment by LinuxSuRen** [comment]
Please help us to test this with the following image:

```
surenpi/ks-console:refactor-select-repo
```

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
image

When I click the selected item after the selection
image

The repo always be `test` when I select a gitlab repo:
image

**Comment by yudong2015** [comment]
test passed

**Pull request merged**
