### PR TITLE
Fix issue: Not found error appears when querying CR on the CRD page

### LINKED ISSUE #1723: Not found error appears when querying CR on the CRD page
**Describe the bug**

Not found error appears when querying CR on the CRD page
query cr not found error

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0
Kubernetes: v1.18.14

**Environment**
3 masters, also as nodes:  88cpu/1T

**To Reproduce**
1. Save this yaml content to file kibana-crd.yaml, then kubectl apply -f kibana-crd.yaml：
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: kibanas.kibana.k8s.elastic.co
spec:
  additionalPrinterColumns:
  - JSONPath: .status.health
    name: health
    type: string
  - JSONPath: .status.availableNodes
    description: Available nodes
    name: nodes
    type: integer
  - JSONPath: .status.version
    description: Kibana version
    name: version
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  group: kibana.k8s.elastic.co
  names:
    categories:
    - elastic
    kind: Kibana
    listKind: KibanaList
    plural: kibanas
    shortNames:
    - kb
    singular: kibana
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1beta1
    served: true
    storage: false
  - name: v1alpha1
    served: false
    storage: false
```

2. http://localhost:8000/clusters/host/customresources/kibanas.kibana.k8s.elastic.co/resources
image
3. click Kibana to query kibana CR

**Expected behavior**

Query  three kibana CR is expected， like kubectl query result：
```shell
# kubectl get kibanas.kibana.k8s.elastic.co  -A
NAMESPACE   NAME        HEALTH   NODES   VERSION   AGE
arch-xadd   kb-pubsub   green    1       7.10.0    81d
arch-xadd   kb-xadd-a   green    1       7.10.0    133d
cdc         kb-cdc-a    green    1       7.10.1    11d
```

### PR DESCRIPTION
**Pull request by liabio**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix bug：Not found error appears when querying CR on the CRD page

**Which issue(s) this PR fixes**:
Fixes #1723

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs


```
fix verify screenshot

### CODE REVIEW

**Comment by liabio** [comment]
> Need to sign off your commit, you can use the following command
> 
> ```
> git commit --amend --no-edit -s && git push -f 
> ```

**Comment by zryfish** [comment]
Why do we close this PR?

**Comment by liabio** [comment]
> Need to sign off your commit, you can use the following command
> 
> ```
> git commit --amend --no-edit -s && git push -f 
> ```

It is ok

**Comment by liabio** [comment]
> Why do we close this PR?

sorry ， I accidentally clicked close ~

**Pull request merged**
