### PR TITLE
feat: Add edit service in the detail of service in the federated project

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Easier to edit service configuration information in multi-cluster projects

**Which issue(s) this PR fixes**:

Fixes ##1916

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```
/assign @xuliwenwenwen

### CODE REVIEW

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/120740625-1d8ad900-c526-11eb-9ac1-6fa5a8edcfce.mp4

**Comment by harrisonliu5** [comment]
In order to transplant this function to the v3.0.0 branch more conveniently, the two-bit code has been merged into the current PR. thank you for your contribution to the development of this function. @xuliwenwenwen @fuchunlan

**Comment by zheng1** [comment]
/assign @yuswift 
PTAL

**Comment by yuswift** [comment]
> PTAL

It looks great. Is there a console image for testing? @harrisonliu5 tks!

**Comment by harrisonliu5** [comment]
> > PTAL
> 
> It looks great. Is there a console image for testing? @harrisonliu5 tks!

This is the image `harrisonliu5/ks-console:fedEdit`

**Comment by yuswift** [comment]
> harrisonliu5/ks-console:fedEdit

thanks 
@wenxin-01 is going to help us test the new feature. Looking forward to his feedback.

**Comment by wenxin-01** [comment]
Some issues need to be fixed https://github.com/kubesphere/console/issues/1943 https://github.com/kubesphere/console/issues/1942  https://github.com/kubesphere/console/issues/1938 https://github.com/kubesphere/console/issues/1937

**Comment by harrisonliu5** [comment]
@wenxin-01 This image `harrisonliu5/ks-console:fedEdit` has updated, and #1937 #1938 #1942 #1943 has fixed. please check them thanks.

**Comment by yuswift** [comment]
Thanks @wenxin-01 and @harrisonliu5  
All of the issues have been closed. Could we merge this pr?

**Comment by wenxin-01** [comment]
> Thanks @wenxin-01 and @harrisonliu5
> All of the issues have been closed. Could we merge this pr?

There are still some outstanding problems.

**Comment by zheng1** [comment]
@wenxin-01 Can you list the others?

**Comment by wenxin-01** [comment]
> @wenxin-01 Can you list the others?

https://github.com/kubesphere/console/issues/1960

**Comment by wenxin-01** [comment]
'service settings' not work in 'Diff Settings' of stateful service   @harrisonliu5 
https://github.com/kubesphere/console/issues/1966

**Pull request merged**
