### PR TITLE
fix: Fix workspace role table not show aliasName

### LINKED ISSUE #2989: Workspace Roles table not show role aliasName
/bug

Workspace Roles table not show role aliasName

### PR DESCRIPTION
**Pull request by moweiwei**
Signed-off-by: moweiwei [moweiwei6@gmail.com](moweiwei6@gmail.com)

### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes ##2989

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
fix: Fix workspace role table not show aliasName
```

### CODE REVIEW

**Comment by harrisonliu5** [comment]
So glad to receive your PR.   but this PR can not fix this issue. Solving this issue with the use `{getDisplayName} from 'utils`， this function is better for you, maybe you can try it again,
Thanks.

**Comment by harrisonliu5** [comment]
I'm so sorry, I forgot to tell you that you should replace the title instead of adding desc, and I hope you could add desc too.
Thanks

**Comment by harrisonliu5** [comment]
Please refer to the picture below for the effect:

image

**Comment by moweiwei** [comment]
thanks, i have add displayName in title, and  des is a column, so it is unnecessary in Avatar

/assign harrisonliu5

**Comment by harrisonliu5** [comment]
Hello, I'm sorry to tell you that the PR description may need to be adjusted with reference to the format of other PRs. Pay special attention to the need for ## in front of the associated issue, and a `release note` is also required.

Thanks

**Comment by harrisonliu5** [comment]
Thanks for your contribution @moweiwei

**Pull request merged**
