### PR TITLE
fix: deselect the svg after performing an action on the svg like editing

### PR DESCRIPTION
**Pull request by fuchunlan**
**What type of PR is this?**

/kind optimization

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes ##793

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by fuchunlan** [comment]
https://user-images.githubusercontent.com/63338728/118100247-d0c15000-b408-11eb-8254-e5bf2bcefed3.mov

**Comment by benjaminhuo** [comment]
The new behaviour looks normal now! thanks @fuchunlan

**Pull request merged**
