### PR TITLE
feat: Add Self-built Kubernetes cluster provider type

### LINKED ISSUE #2121: Add Self-built Kubernetes cluster provider type
**What would you like to be added**:
Add Self-built Kubernetes cluster provider type

**Why is this needed**:
In xiaomi, we have many self-built k8s clusters and we want to manage them using kubesphere

### PR DESCRIPTION
**Pull request by lshmouse**
### What this PR does / why we need it:
See: https://github.com/kubesphere/console/issues/2121 

### Which issue(s) this PR fixes:
Fixes #2121

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?
[
x
](url)

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by harrisonliu5** [comment]
Please Follow the [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) to modify the comment title. And the modified issue address should be in `which issue (s) this PR fixes: `. 

At last, thank you for your contribution to Kubesphere.

**Comment by lshmouse** [comment]
> Please Follow the [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) to modify the comment title. And the modified issue address should be in `which issue (s) this PR fixes: `.
> 
> At last, thank you for your contribution to Kubesphere.

done, thanks for your review~

**Comment by zryfish** [comment]
@lshmouse Thanks for your PR, it's very welcome. But there is a question, why do we need another option `Self-Built Kubernetes` since the provider Combobox is editable. You can type any provider field as you like.

截屏2021-07-28 14 24 59

**Comment by lshmouse** [comment]
> @lshmouse Thanks for your PR, it's very welcome. But there is a question, why do we need another option `Self-Built Kubernetes` since the provider Combobox is editable. You can type any provider field as you like.
> 
> 截屏2021-07-28 14 24 59

Thanks very mush for pointing this.    That the provider Combobox is editable is perfect~

**Pull request closed without merging**
