### PR TITLE
fix: Trusted User in multi-branch pipeline

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes ##1898

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

/assign @LinuxSuRen

### CODE REVIEW

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/118586230-f36ab480-b7cc-11eb-972d-563109c08780.mp4

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Review by LinuxSuRen — APPROVED** [review]

**Comment by harrisonliu5** [comment]
> I got some errors when I try to run it. I know it might have not relation with this PR.
> 
> ```
>     ERROR in ./src/components/Modals/Bill/components/Crumb/index.scss (./node_modules/css-loader??ref--7-1!./node_modules/sass-loader/dist/cjs.js!./src/components/Modals/Bill/components/Crumb/index.scss)
>     Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
>     
>     @import '~scss/variables';
>     ^
>           File to import not found or unreadable: ~scss/variables.
>           in /workspace/console/src/components/Modals/Bill/components/Crumb/index.scss (line 1, column 1)
>      @ ./src/components/Modals/Bill/components/Crumb/index.scss 2:14-155 21:1-42:3 22:19-160
>      @ ./src/components/Modals/Bill/components/Crumb/index.jsx
>      @ ./src/components/Modals/Bill/Details/Cluster/index.jsx
>      @ ./src/components/Modals/Bill/Details/index.jsx
>      @ ./src/components/Modals/Bill/index.jsx
>      @ ./src/pages/console/containers/Bill/index.jsx
>      @ ./src/pages/console/routes/index.js
>      @ ./src/pages/console/App.jsx
>      @ ./src/core/routes.js
>      @ ./src/core/App.jsx
>      @ ./src/core/index.js
>      @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/core/index.js
>     
>     ERROR in ./src/components/Modals/Bill/components/SideCard/item.scss (./node_modules/css-loader??ref--7-1!./node_modules/sass-loader/dist/cjs.js!./src/components/Modals/Bill/components/SideCard/item.scss)
>     Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
>     
>     @import '~scss/variables';
>     ^
>           File to import not found or unreadable: ~scss/variables.
>           in /workspace/console/src/components/Modals/Bill/components/SideCard/item.scss (line 1, column 1)
>      @ ./src/components/Modals/Bill/components/SideCard/item.scss 2:14-154 21:1-42:3 22:19-159
>      @ ./src/components/Modals/Bill/components/SideCard/item.jsx
>      @ ./src/components/Modals/Bill/components/SideCard/index.jsx
>      @ ./src/components/Modals/Bill/Details/Cluster/index.jsx
>      @ ./src/components/Modals/Bill/Details/index.jsx
>      @ ./src/components/Modals/Bill/index.jsx
>      @ ./src/pages/console/containers/Bill/index.jsx
>      @ ./src/pages/console/routes/index.js
>      @ ./src/pages/console/App.jsx
>      @ ./src/core/routes.js
>      @ ./src/core/App.jsx
>      @ ./src/core/index.js
>      @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/core/index.js
> ```

you should restart the node environment

**Comment by LinuxSuRen** [comment]
> I got some errors when I try to run it. I know it might have not relation with this PR.

Thanks for the explanation. It works.

**Pull request merged**
