### PR TITLE
feat: Support set gpu limit of project quota

### PR DESCRIPTION
**Pull request by weili520**
Signed-off-by: TheYoungManLi <cjl@kubesphere.io>

### What type of PR is this?
/kind feature

### Which issue(s) this PR fixes:
Fixes #

### Special notes for reviewers:
https://user-images.githubusercontent.com/33231138/133749024-dde7a876-61da-4bf4-b54b-4455276f9e88.mov
### Does this PR introduced a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by zhu733756** [comment]
For resourcequota，it makes no sense to specify both requests and limits for the same extended resource in a quota. Only need to set requests.xxx.  Refer to https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-for-extended-resources

For workload GPU resources, only need to set limits(if you set requests, should keep them the same with each other). Refer to https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins

**Comment by benjaminhuo** [comment]
> For resourcequota，it makes no sense to specify both requests and limits for the same extended resource in a quota. Only need to set requests.xxx. Refer to https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-for-extended-resources
> 
> For workload GPU resources, only need to set limits(if you set requests, should keep them the same with each other). Refer to https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins

Yeah, only limit is need for GPU.
And @zhu733756 , we should only add nvidia gpu type in the list

**Pull request merged**
