### PR TITLE
feat: Add shell access to nodes

### PR DESCRIPTION
**Pull request by lynxcat**
### What type of PR is this?

/kind feature

### What this PR does / why we need it:
This function can make it easier for us to manage the edge host, such as

+ Download Image before updating edge application
+ Update edgecore or docker at the edge
+ Modify the edge host configuration
+ ...
### Which issue(s) this PR fixes:

Fixes #
issue: [kubesphere#4569](https://github.com/kubesphere/kubesphere/issues/4569)

### Special notes for reviewers:
```
None
```

### Does this PR introduced a user-facing change?

added a button in nodes page
image

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by zryfish** [comment]
Just tried in my environment, the right-side panel shows the same tips as the kubectl terminal, which is very confusing. I think we need to replace it with something more descriptive

Screenshot 2022-01-10 at 16 25 22

**Comment by lynxcat** [comment]
@zryfish Can I block this tips, I'm not too familiar with front-end code

**Comment by zryfish** [comment]
Could you create a issue to track this? I think we'd better keep the right-panel tips, for example, we can add some text there to warn users not to do something dangerous.

**Comment by lynxcat** [comment]
ok, i created an issue: #2902

**Comment by zryfish** [comment]
thx, we can discuss details there

**Pull request merged**
