### PR TITLE
fix: Add empty message in repo form

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

 /kind optimization

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

/assign @leoendless 
/assign @LinuxSuRen 
/project devops

### CODE REVIEW

**Comment by harrisonliu5** [comment]
image

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
