### PR TITLE
fix: Modify the sync api

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>

### What type of PR is this?

/kind api-change

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
NONE
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Please feel free to use the following image if you want to help us to test it:
```
surenpi/ks-console:latest@sha256:78091a8b326583e8e7431b604c9df0b20f25ef4494ca92a2ce3a9b88e9d04a78
```

**Review by JohnNiang — COMMENTED** [review]
How about setting the two options to a default value?

image

**Comment by LinuxSuRen** [comment]
> How about setting the two options to a default value?

Would you mind telling us some use cases that are suitable for those default values?

**Comment by JohnNiang** [comment]
> > How about setting the two options to a default value?
> 
> Would you mind telling us some use cases that are suitable for those default values?

That's my mistake. Please ignore me.

**Review by LinuxSuRen — APPROVED** [review]
I have tested it manually. It works well. Thanks for your effort.
/lgtm

**Pull request merged**
