### PR TITLE
fix: Sonarqube testing bug

### PR DESCRIPTION
**Pull request by weili520**
Signed-off-by: TheYoungManLi <cjl@kubesphere.io>

### What type of PR is this?
/kind bug

### Which issue(s) this PR fixes:
Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @weili520, could you tell us what happened before this PR? I'm very concerned about SonarQube.

**Comment by weili520** [comment]
> Hi @weili520, could you tell us what was wrong before this PR? I'm very concerned about SonarQube.

It just some  syntax and regular expression errors.

**Comment by JohnNiang** [comment]
> > Hi @weili520, could you tell us what was wrong before this PR? I'm very concerned about SonarQube.
> 
> It just some syntax and regular expression errors.

Thanks for your excellent explanation!

**Pull request merged**
