### PR TITLE
Recipient UI Text Update

### PR DESCRIPTION
**Pull request by Sherlock113**
Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Minor fix. Recipient is commonly used for notifications.

### CODE REVIEW

**Comment by Sherlock113** [comment]
/assign @leoendless
Thanks.

**Comment by leoendless** [comment]
@benjaminhuo @FeynmanZhou Please help to reviews these changes.

**Review by benjaminhuo — APPROVED** [review]
good cache
Looks good to me

**Review by FeynmanZhou — APPROVED** [review]

**Pull request merged**
