### PR TITLE
fix: Modify the style of Select

### PR DESCRIPTION
**Pull request by fuchunlan**
Signed-off-by: lannyfu <lannyfu@yunify.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #[#kubusphere/kubusphere/3488](https://github.com/kubesphere/kubesphere/issues/3488)

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

https://user-images.githubusercontent.com/63338728/121324753-9aadb800-c943-11eb-9e5a-e37ee4c90726.mov

```docs

```

### CODE REVIEW

**Comment by harrisonliu5** [comment]
The minimum width should be the same as the width of the input box @fuchunlan

**Comment by fuchunlan** [comment]
> The minimum width should be the same as the width of the input box @fuchunlan

image

**Pull request merged**
