### PR TITLE
Refactor with PipelineRun listing and creation API

### PR DESCRIPTION
**Pull request by JohnNiang**
### What type of PR is this?

/kind api-change
/area devops
/milestone v3.2

### What this PR does / why we need it:

- Refactor with PipelineRun listing API
- Refactor with PipelineRun creation API

We have made some API changes in DevOps area. Please see:

- https://github.com/kubesphere/ks-devops/pull/230
- https://github.com/kubesphere/ks-devops/pull/233

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
Docker image for test: `johnniang/ks-console:pipeline-run-api`
```

### Does this PR introduced a user-facing change?

```release-note
Refactor with PipelineRun listing and creation API
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Please check if this PR is still in the progress. @JohnNiang

**Comment by JohnNiang** [comment]
> Please check if this PR is still in the progress. @JohnNiang

Yup, it's in WIP status, Because https://github.com/kubesphere/ks-devops/pull/238 might change the API version.

**Pull request merged**
