### PR TITLE
feat: Add Grafana dashboard in custom monitoring

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

### What type of PR is this?

/kind feature

### Which issue(s) this PR fixes:

Fixes ##https://github.com/kubesphere/kubesphere/pull/4194

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Add Grafana dashboard in custom monitoring
```

### Additional documentation, usage docs, etc.:

```docs

```

/assign @zhu733756

### CODE REVIEW

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/131797671-5a39a213-3c86-4403-9c2a-a5eb17f72e26.mp4

**Comment by zhu733756** [comment]
Seems so great. Btw, Can we use link to import Grafana templates?

**Comment by harrisonliu5** [comment]
> Seems so great. Btw, Can we use the link to import Grafana templates?

Yes , it works well

**Pull request merged**
