### PR TITLE
fix: When creating a CD task, selecting ‘replace resource' did not take effect

### PR DESCRIPTION
**Pull request by weili520**
Signed-off-by: TheYoungManLi <cjl@kubesphere.io>

### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:
Fixes ##3209

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
```
surenpi/ks-console:devops_sync@sha256:7ed1a9183b42378440dec276ab3eda3cec0527be40db5f8db23f04fce26064f9
```

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
When I test it manually, I found a checkbox cannot be checked. See the following screenshot.

image

**Comment by weili520** [comment]
> When I test it manually, I found a checkbox cannot be checked. See the following screenshot.
> 
> image

fix it now.

**Comment by weili520** [comment]
https://user-images.githubusercontent.com/33231138/165892955-8abf0120-feea-4964-a1ca-75a1c5dcc44f.mov

**Review by LinuxSuRen — COMMENTED** [review]
I have tested it manually. It works well. Thanks for your effort!

LGTM

**Pull request merged**
