### PR TITLE
add build support for multiple platforms

### PR DESCRIPTION
**Pull request by zryfish**
### What type of PR is this?
/kind cleanup
/kind feature

### What this PR does / why we need it:
1. Currently, console build doesn't support multiple platforms, only targeted `linux/amd64`. There is an increasing trend for `linux/arm64`. This PR add supports for build container targeted both `linux/amd64` and `linux/arm64`.
2. Cleanup unused files

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by harrisonliu5** [comment]
Please pay attention that it is not recommended to delete that the verification files of the code specification.  (`.editorconfig`, `.eslintignore`, `.eslintrc.js`, `.gitignore`, `.prettierignore`,  `.prettierrc`)  @zryfish

**Comment by zryfish** [comment]
Where there is will, there is a way.

**Pull request merged**
